# -*- coding: utf-8 -*-
"""Task-2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pJGYjP-AlsR6_mRKbv1Z-xFu7lJx5G20
"""

import pandas as pd
import matplotlib.pyplot as plt

"""Python Script"""

data = pd.read_csv("/content/drive/MyDrive/Task2p1/Task2p1_0.csv")
data
data = pd.read_csv("/content/drive/MyDrive/Task2p1/Task2p1_1.csv")
data

"""Jupyter Notebook"""

data = pd.read_csv("/content/drive/MyDrive/Task2p1/Task2p1_0.csv")

data

data = pd.read_csv("/content/drive/MyDrive/Task2p1/Task2p1_1.csv")

data

#The difference is that in python script only the data that is in Task2p1_1 is getting printed(because in python script the "data" value in the program has been changed and hence it has been only printing the result that has been assigned to it in later)  while when we run the code in Jupyter Notebook line by line we see that both the results/outcomes(Task2p1_0 and Task2p1_1)are getting printed

"""The difference is that in python script only the data that is in Task2p1_1 is getting printed(because in python script the "data" value in the program has been changed and hence it has been only printing the result that has been assigned to it in later)  while when we run the code in Jupyter Notebook line by line we see that both the results/outcomes(Task2p1_0 and Task2p1_1)are getting printed"""